AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  postgres-lambda-trigger

  Sample SAM Template for postgres-lambda-trigger
Parameters:
  DBNAMEPARAM:
    Description: The DB Name
    Type: String
    Default: demo
  DBUSERPARAM:
    Description: The DB User Name
    Type: String
    Default: master

Globals:
  Function:
    Environment: 
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        DB_MASTER_SECRET_ARN: !GetAtt RDSStack.Outputs.SecretArn
        DB_ENDPOINT: !GetAtt RDSStack.Outputs.Endpoint
        DB_NAME: !Ref DBNAMEPARAM
    CodeUri: .
    Architectures:
        - arm64
    Runtime: java11
    Timeout: 60
    MemorySize: 1024

Resources:
  
      
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: postgres.yaml
      TimeoutInMinutes: '60'
      Parameters:
        DBNAMEPARAM: !Ref DBNAMEPARAM
        DBUSERPARAM: !Ref DBUSERPARAM
        
  ApiGateway:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration: true
            
  FrontEnd:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-DemoFrontEnd
      Description: Displays Sample Postgres Table and allows Address Entry
      Handler: demo.FrontEnd
      Policies: 
        - !Ref SecretsPolicy
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
            ApiId: !Ref ApiGateway
    
  PostgresAddressTrigger:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostgresAddressTrigger
      Description: Lambda that will fire when changes are made to Address Table
      Handler: demo.PostgresAddressTrigger
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 300
        MaximumRetryAttempts: 1
      Policies: 
        - !Ref SecretsPolicy  
            
  PostgresGenericTrigger:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostgresGenericTrigger
      Description: Lambda that will fire when changes are made to tables
      Handler: demo.PostgresGenericTrigger
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 300
        MaximumRetryAttempts: 1
      Policies: 
        - !Ref SecretsPolicy          
            
   
  DBInitialization:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-DBInitialization
      Description: Performs the DB Scripting after DB creation
      Handler: demo.CloudFormationCustomResource
      Timeout: 120
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 300
        MaximumRetryAttempts: 1
      Policies: 
        - !Ref SecretsPolicy
            
  
  DBCustom:
    Type: Custom::DBInitialization
    DependsOn: RDSStack  # Make sure the RDS instance is done before we run DB Scripts
    Properties:
        ServiceToken: !GetAtt DBInitialization.Arn

  SecretsPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
        Description: Allow Lambdas to access the RDS Managed Secret
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:DescribeSecret'
                Resource: !GetAtt RDSStack.Outputs.SecretArn
   


Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt ApiGateway.ApiEndpoint
  DBEndpoint:
    Description: "DB Endpoint"
    Value: !GetAtt RDSStack.Outputs.Endpoint
     
