
name: Build AWS SAM Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    
    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
        
    - name: SAM Build
      run: sam build
      
#    - name: Install and run cfn-lint
#      uses: scottbrenner/cfn-lint-action@v2
#      with:
#          command: cfn-lint -t ./template.yml

   
    


