
name: Build AWS SAM Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

      # Having SAM build inside container then removes all Maven/Java requirements
      #  The image SAM pulls will build the lambda correctly
    - name: Build inside Docker containers
      run: sam build --use-container
    


