
name: Java CI with AWS SAM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

      # Having SAM build inside container then removes all Maven/Java requirements
      #  The image SAM pulls will build the lambda correctly
    - name: Build inside Docker containers
      run: sam build --use-container
    
    #- name: Setup AWS Creds
    #  uses: aws-actions/configure-aws-credentials@v4
    #  with:
    #    aws-region: us-east-1
    #    role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      
    #- name: Prevent prompts and failure when the stack is unchanged
    #  run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset


